
exports = [
  'src/prefix.js',
  'src/shortcuts.js',
  'node_modules/color/dist/Color.debug.js',
  'src/lib/SunPosition.js',
  'src/GeoJSON.js',
  'src/variables.js',
  'src/geometry.js',
  'src/functions.js',
  'src/Request.js',
  'src/Data.js',
  'src/geometry/Block.js',
  'src/geometry/Cylinder.js',
  'src/geometry/Pyramid.js',
  'src/layers/Buildings.js',
  'src/layers/Simplified.js',
  'src/layers/Shadows.js',
  'src/layers/HitAreas.js',
  'src/layers/Debug.js',
  'src/Layers.js',
  'src/adapter.js',
  'src/engines/{engine}.js',
  'src/public.js',
  'src/suffix.js'
];
